os: linux
language: android
jdk: openjdk11

env:
  global:
    - TARGET_SDK=33
    - BUILD_TOOLS=33.0.0
    - ANDROID_HOME=~/android-sdk

android:
  components:
    - tools
    - platform-tools

before_install:
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O "commandlinetools.zip"
  - unzip "commandlinetools.zip" -d "$ANDROID_HOME"/
  - yes | "$ANDROID_HOME"/cmdline-tools/bin/sdkmanager "platforms;android-$TARGET_SDK" --sdk_root="$ANDROID_HOME"
  - yes | "$ANDROID_HOME"/cmdline-tools/bin/sdkmanager "build-tools;$BUILD_TOOLS" --sdk_root="$ANDROID_HOME"

script:
  - ./gradlew check --info
  - ./gradlew jacocoTestReport

after_success:
  - curl -Os "https://uploader.codecov.io/latest/linux/codecov"
  - chmod +x codecov
  - ./codecov

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
